[package]
name = "pixelfold-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pixelfold"
path = "src/main.rs"

[dependencies]
pixelfold-core.workspace = true

anyhow.workspace = true
bytes.workspace = true
crossterm.workspace = true
flate2.workspace = true
futures.workspace = true
glam.workspace = true
nom.workspace = true
ratatui.workspace = true
rayon.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
