[package]
name = "pixelfold-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pixelfold-core.workspace = true
pixelfold-render.workspace = true
pixelfold-fetch.workspace = true

anyhow.workspace = true
crossterm.workspace = true
futures.workspace = true
glam.workspace = true
image.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
serde.workspace = true
tokio.workspace = true
